---
- name: Create inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add nodes
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_ssh_host: "{{ item }}"
        ansible_ssh_port: "{{ lookup('ansible.builtin.env', 'BASTION_PORT') }}"
        ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'BASTION_USER') }}"
        ansible_ssh_pass: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"
        ansible_python_interpreter: /usr/libexec/platform-python
      loop:
        - controller
        - vscode

- name: setup controller for network use cases
  hosts: controller
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    aap_hostname: localhost
    aap_username: admin
    aap_password: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"
    aap_validate_certs: false
  tasks:
    - name: Get job templates from Automation Controller
      uri:
        url: https://{{ aap_hostname }}/api/controller/v2/job_templates/
        method: GET
        validate_certs: "{{ aap_validate_certs }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password}}"
        force_basic_auth: yes
      register: job_templates

    - name: Print job template names
      debug:
        msg: "{{ job_templates.json.results | map(attribute='name') | list }}"
    
    - name: Extract job template names
      set_fact:
        template_names: "{{ job_templates.json.results | map(attribute='name') | list }}"

    - name: Get job templates from Automation Controller
      uri:
        url: https://{{ aap_hostname }}/api/controller/v2/jobs/
        method: GET
        validate_certs: "{{ aap_validate_certs }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password}}"
        force_basic_auth: yes
      register: jobs

    - name: Extract job names
      set_fact:
        job_names: "{{ jobs.json.results | map(attribute='name') | list }}"

    - name: Fail template Network Automation - Backup is not found
      validation_check:
        error_msg: "Job template 'Network Automation - Backup' does not exist in Automation Controller!"
        check: "'Network Automation - Backup' in template_names"

    - name: Fail template Network Automation - Restore is not found
      validation_check:
        error_msg: "Job template 'Network Automation - Restore' does not exist in Automation Controller!"
        check: "'Network Automation - Restore' in template_names"

    - name: Fail Job Network Automation - Restore is not found
      validation_check:
        error_msg: "Job template 'Network Automation - Restore' has not been launched in the Automation Controller!"
        check: "'Network Automation - Restore' in job_names"
  
